### ISSUE TITLE
nanopb error during build

### ISSUE THREAD

**Issue by csBlueChip** [csBlueChip/FlipperZero_plugin_howto#5]
After a fresh download on a newly installed machine (debian 12), `./fbt` generates this error:
```
        PROTO   assets/protobuf/application.proto
Traceback (most recent call last):
  File "/home/fz/official/./lib/nanopb/generator/nanopb_generator.py", line 51, in <module>
    from .proto import nanopb_pb2
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fz/official/./lib/nanopb/generator/nanopb_generator.py", line 72, in <module>
    import proto.nanopb_pb2 as nanopb_pb2
ModuleNotFoundError: No module named 'proto.nanopb_pb2'
scons: *** [build/f7-firmware-D/assets/compiled/application.pb.c] Error 1

********** FBT ERRORS **********
build/f7-firmware-D/assets/compiled/application.pb.c: Error 1
```

**Comment by csBlueChip** [comment]
You need to install the nanopb dev libraries:
```
apt-get install libnanopb-dev
```

I have updated the readme.
